apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sqlserver-deplo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sqlserver-label
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: sqlserver-container
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports:
          - containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Developer"
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlserver-password
                key: SA_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
spec:
  selector:
    app: sqlserver-label
  ports:
   - protocol: TCP
     port: 1433
     targetPort: 1433
  type: LoadBalancer